/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PackageFrm;

import Conexion.Conexion;
import Conexion.ConexionDes;
import Conexion.ConexionOri;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADRIAN
 */
public class IrpRucCom extends javax.swing.JInternalFrame {

    /**
     * Creates new form IrpRucCom
     */
    public IrpRucCom() {
        initComponents();
    }
    String Proceso = "";
    int selectcount = 0;
    int setRowCount = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);

        jButton1.setText("Actualizar Facturas RucCom (IRP)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Proceso", "Cantidad de Registros Procesado"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Actualizar Tilde (No Enviar)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Limpiar Tabla");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void CargarGrid(){        
        JTable table = null;
        JScrollPane ScrollPane;
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        if(setRowCount==0){
           modelo.setRowCount(0);
        }
        try {
             Vector v = new Vector();
             v.add(Proceso);
             v.add(selectcount);
             modelo.addRow(v);
             jTable1.setModel(modelo);
             ScrollPane = new JScrollPane(table);
             jTable1.add(ScrollPane,BorderLayout.CENTER); 
             setRowCount++;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex, "Error"+ex.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PreparedStatement QueryDelete = null;
        try {        
        Connection con23 = ConexionDes.GetConnection();                                                                                                                                                                                                                                                                                              //1                                //2                   //3              //4               //5          //6    //7//8                          //9                     //10     //11     //12      //13               //14            //15            //16            //17            //18            //19    //20
        QueryDelete = con23.prepareStatement("Delete From COMIRP");
        QueryDelete.execute();
        con23.close();                    
        } catch (SQLException e) {
        }        
        
        Proceso = "Actualizar Facturas RucCom (IRP)";
        int canttot = 0;
        int NoEnviar = 0;
        PreparedStatement query = null;
        try {
            
            Connection con = ConexionOri.GetConnection();
            java.sql.Statement cm=con.createStatement();
            ResultSet rs= cm.executeQuery("SELECT GenRanDId,GenRanId,GenRanDetGasto AS Importe,GenranDitemI,GenRanDiTemG as IrpIn,GenRanDiTemG2 as IrpInV3,GenRanDiTemG3 as IrpInV32,GenRanEmp FROM GENRANDET");
            while(rs.next()){
                
                int GenranDitemI = rs.getInt("GenranDitemI");
                long Importe1 = 0;
                long Importe2 = 0;
                long Importe3 = 0;
                
                //gasto, Inv.Act.Gravada, Inv.Personal
                switch (GenranDitemI) {

                    case 0:
                        Importe1 = rs.getLong("Importe");
                        Importe2 = 0;
                        Importe3 = 0;
                    break;    
                    case 1:
                        Importe1 = 0;
                        Importe2 = rs.getLong("Importe");
                        Importe3 = 0;
                    break;
                    case 2:
                        Importe1 = 0;
                        Importe2 = 0;
                        Importe3 = rs.getLong("Importe");
                    break;
                }
                
                int IrpIn    =   rs.getInt("IrpIn");
                int IrpInV3  =   rs.getInt("IrpInV3");
                int IrpInV32 =   rs.getInt("IrpInV32");
                int stm5,stm11,stm6,stm16,stm14,stm15,stm18,stm17,stm19 = 0;
                
                if(IrpInV3 != 0){
                    switch (IrpInV3) {
                        case 1:
                            IrpInV3 = 156;
                            break;
                        case 2:
                            IrpInV3 = 157;
                            break;
                        case 3:
                            IrpInV3 = 158;
                            break;
                        case 4:
                            IrpInV3 = 159;
                            break;
                        case 5:
                            IrpInV3 = 160;
                            break;
                        case 6:
                            IrpInV3 = 161;
                            break;
                        case 7:
                            IrpInV3 = 162;
                            break;
                        case 8:
                            IrpInV3 = 163;
                            break;
                        case 9:
                            IrpInV3 = 164;
                            break;
                        case 10:
                            IrpInV3 = 165;
                            break;
                        case 11:
                            IrpInV3 = 166;
                            break;
                        case 12:
                            IrpInV3 = 170;
                            break;
                        case 13:
                            IrpInV3 = 171;
                            break;
                        case 14:
                            IrpInV3 = 172;
                            break;
                        case 15:
                            IrpInV3 = 173;
                            break;
                        case 16:
                            IrpInV3 = 174;
                            break;
                        case 17:
                            IrpInV3 = 178;
                            break;
                        case 18:
                            IrpInV3 = 179;
                            break;
                        case 19:
                            IrpInV3 = 180;
                            break;
                        case 20:
                            IrpInV3 = 182;
                            break;
                        case 21:
                            IrpInV3 = 183;
                            break;
                        case 22:
                            IrpInV3 = 175;
                            break;
                        case 23:
                            IrpInV3 = 176;
                            break;
                    }                           
                }                                                      
                
                if(IrpInV32 != 0){
                    switch (IrpInV32) {
                        case 1:
                            IrpInV32 = 156;
                            break;
                        case 2:
                            IrpInV32 = 157;
                            break;
                        case 3:
                            IrpInV32 = 158;
                            break;
                        case 4:
                            IrpInV32 = 159;
                            break;
                        case 5:
                            IrpInV32 = 160;
                            break;
                        case 6:
                            IrpInV32 = 161;
                            break;
                        case 7:
                            IrpInV32 = 162;
                            break;
                        case 8:
                            IrpInV32 = 163;
                            break;
                        case 9:
                            IrpInV32 = 164;
                            break;
                        case 10:
                            IrpInV32 = 165;
                            break;
                        case 11:
                            IrpInV32 = 166;
                            break;
                        case 12:
                            IrpInV32 = 167;
                            break;
                        case 13:
                            IrpInV32 = 168;
                            break;
                        case 14:
                            IrpInV32 = 169;
                            break;
                        case 15:
                            IrpInV32 = 171;
                            break;
                        case 16:
                            IrpInV32 = 172;
                            break;
                        case 17:
                            IrpInV32 = 173;
                            break;
                        case 18:
                            IrpInV32 = 174;
                            break;
                        case 19:
                            IrpInV32 = 175;
                            break;
                    }                    
                }
                
                if(IrpInV32!=0 || IrpInV3 !=0 ){                    
                    if(GenranDitemI==0){
                        stm5 = 1;
                        stm11 = 1;
                    }else{
                        stm5 = 3;
                        stm11 = 2;
                    }
                }else {
                    if(GenranDitemI==0){
                        stm5 = 1;
                    }else{
                        stm5 = 2;
                    }
                    stm11 = 0;
                }
                    
                if (IrpInV32 !=0){
                    stm6 = IrpInV32;
                    stm14 = IrpInV32;
                    stm16 = 0;
                    stm18 = 0;
                    if(GenranDitemI==0){
                        stm15 = 1;
                    }else{
                        stm15 = 3;
                    }
                }else if (IrpInV3 !=0){
                    stm6 = IrpInV3;
                    stm14 = 0;
                    stm16 = IrpInV32;
                    stm18 = 0;
                    stm15 = 0;
                }else{
                    stm6 = IrpIn;
                    stm14 = 0;
                    stm16 = 0;
                    stm18 = IrpIn;
                    stm15 = 0;
                }
                    
                if(IrpInV3!=0){
                    if(GenranDitemI==0){
                        stm17 = 1;
                    }else{
                        stm17 = 3;
                    }
                }else{
                    stm17 = 0;
                }

                if(IrpIn!=0){
                    if(GenranDitemI==0){
                        stm19 = 1;
                    }else{
                        stm19 = 2;
                    }
                }else{
                    stm19 = 0;
                }                    
                    
                Connection con2 = ConexionDes.GetConnection();                                                                                                                                                                                                                                                                                              //1                                //2                   //3              //4               //5          //6    //7//8                          //9                     //10     //11     //12      //13               //14            //15            //16            //17            //18            //19    //20
                query = con2.prepareStatement("INSERT INTO COMIRP (ComIrpId,ComIrpRucComId,ComIrpImpGas,ComIrpImpInv,ComIrpRub,ComIrpIn,ComIrpRucComTot,ComIrpTip,ComIrpEmp,ComIrpCod,ComIrpEst,ComIrpEstMig,ComIrpImpInv2,ComIrpIncV3B,ComIrpRubV3B,ComIrpIncV3,ComIrpRubV3,ComIrpIncV2,ComIrpRubV2,ComIrpMar) VALUES ('"+ rs.getDouble("GenRanDId") +"', '"+ rs.getDouble("GenRanId") +"', '"+ Importe1 +"', '"+ Importe2 +"', '"+ stm5 +"', '"+ stm6 +"', 0, 0, '"+ rs.getString("GenRanEmp").replace(" ","") +"', 0, '"+ stm11 +"', 0, '"+ Importe3 +"', '"+  stm14 +"', '"+  stm15 +"', '"+  stm16 +"', '"+  stm17 +"', '"+  stm18 +"', '"+  stm19 +"', 0)");
                query.execute();
                con2.close();
                selectcount++;                
            }            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex, "Error"+ex.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
        CargarGrid();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PreparedStatement query = null;        
        Proceso = "Actualizar Tilde No Enviar";
        selectcount = 0;
        try {
            Connection con = ConexionOri.GetConnection();
            java.sql.Statement cm=con.createStatement();
            ResultSet rs= cm.executeQuery("select * from GenRan");
            while(rs.next()){
                Connection con2 = ConexionDes.GetConnection();
                query = con2.prepareStatement("Update RucCom Set RucComNoEnv = ? Where RucComId = ? and RucComEmp = ?");
                query.setInt(1, rs.getInt("GenRanEst"));
                query.setInt(2, rs.getInt("GenRanId"));
                query.setString(3, rs.getString("GenRanEmp"));
                query.execute();                          
                selectcount++;
                System.out.println("Lineas: " + selectcount);
            }            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex, "Error en GenRan "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);  
        }
        CargarGrid();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Proceso = "Tabla Limpiada";
        PreparedStatement query = null;   
        try {
            Connection con2 = ConexionOri.GetConnection();
            query = con2.prepareStatement("delete from genran where GenRanId not in (Select RucComId From RucCom)");
            query.execute();
        } catch (SQLException e) {
        }        
        CargarGrid();
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
