/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PackageFrm;

import Conexion.Conexion;
import Conexion.ConexionDes;
import Conexion.ConexionOri;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADRIAN
 */
public class Migracion2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Migracion2
     */
    public Migracion2() {
        initComponents();
        cargargrid();
    }
    ArrayList<String> canciones = new ArrayList<>();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Migracion Tablas Secundarias");
        setPreferredSize(new java.awt.Dimension(840, 677));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tabla", "Cantidad de Registro"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tabla", "Cantidad de Registro Migrado"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("Migrar todas las tablas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cantidad de Tablas:");

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cantidad de Registros:");

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad de Tablas Migradas");

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad de Registros Migrados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField2))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Migracion();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void cargargrid (){
        JTable table = null;
        JScrollPane ScrollPane;
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
        int tablas = 0;
        int cantidad = 0;
        canciones.add("BALGRAL");
        canciones.add("AJUSTECAMBIO");
        canciones.add("BDAUXILIARESSALARIO");
        canciones.add("BDBALANCEVERIF");
        canciones.add("BDCOBRO");
        canciones.add("BDCONFIGURACION");
        canciones.add("BDDOCUMENTOS");
        canciones.add("BDDOCUMENTOSCAB");
        canciones.add("BDFACTURA");
        canciones.add("BDGENCOBRO");
        canciones.add("BDGENFACTURA");
        canciones.add("BDHONOPROF");
        canciones.add("BDMESAJEH");
        canciones.add("BDMESAJEHLEVEL1");
        canciones.add("BDOBLIGACIONES");
        canciones.add("BDOBLIGACIONES2");
        canciones.add("BDOBLIGACIONESDET");
        canciones.add("BDPRESOBLI");
        canciones.add("BDREMBOLSO");
        canciones.add("BDREMBOLSODET");
        canciones.add("BDSERVICIOS");
        canciones.add("BDSERVVARIOS");
        canciones.add("BDTAREAS");
        canciones.add("BDTAREASVARIAS");
        canciones.add("BDTIMBAJA");
        canciones.add("BDUSUASIG");
        canciones.add("BDUSUULTMSG");
        canciones.add("BDVISITA");
        canciones.add("BDVISITASPROG");
        canciones.add("CANCUORET");
        canciones.add("CHEQUERA");
        canciones.add("CNFRUCOM");
        canciones.add("CNFRUCVEN");
        canciones.add("COEFICIENTE");
        canciones.add("COMEXPORT");
        canciones.add("CONCEPTO");
        canciones.add("CONFREV");
        canciones.add("CUENTAMHR110");
        canciones.add("DETTESAKA");
        canciones.add("FORMATO");
        canciones.add("FORMATOV");
        canciones.add("NIVELES");
        canciones.add("PAGO");
        canciones.add("PERMISO");
        canciones.add("PRESENTACION");
        canciones.add("PRESUPUESTO");
        canciones.add("RECTIFICATIVA");
        canciones.add("RESPONSABLE");
        canciones.add("RESPONSABLELEVEL1");
        canciones.add("RETENCION");
        canciones.add("SOLPAG");
        canciones.add("SUCURSAL");
        canciones.add("TRNFCTA");
        try {
           for (String cancion : canciones) {
               Vector v = new Vector();
               v.add(cancion);
            Connection con = ConexionOri.GetConnection();
            java.sql.Statement cm=con.createStatement();
            ResultSet rs= cm.executeQuery("SELECT count(*) FROM " + cancion + "");
            while(rs.next()){
                     v.add(rs.getLong(1));
                     cantidad += rs.getLong(1);
                     v.add("No");
            }
            modelo.addRow(v);
            jTable1.setModel(modelo);
            ScrollPane = new JScrollPane(table);
            jTable1.add(ScrollPane,BorderLayout.CENTER);
            tablas++;
           }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex, "Error al Cargar Grilla 1, Posible Error de Conxion con la BD"+ex.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
        jTextField1.setText(String.valueOf(tablas));
        jTextField4.setText(String.valueOf(cantidad));
    }        
    
    public void cargagriddes(){
        JTable table = null;
        JScrollPane ScrollPane;
        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
        modelo.setRowCount(0);
        int tablas = 0;
        int cantidad = 0;
        try {
           for (String cancion : canciones) {
               Vector v = new Vector();
               switch(cancion){
                   case"FORMATOV":
                       cancion = "TIMCLIENTE";
                   break;
               }
               v.add(cancion);
            Connection con = ConexionDes.GetConnection();
            java.sql.Statement cm=con.createStatement();
            ResultSet rs= cm.executeQuery("SELECT count(*) FROM " + cancion + "");
            while(rs.next()){
                     v.add(rs.getLong(1));
                     cantidad += rs.getLong(1);
                     v.add("No");
            }
            modelo.addRow(v);
            jTable2.setModel(modelo);
            ScrollPane = new JScrollPane(table);
            jTable2.add(ScrollPane,BorderLayout.CENTER);
            tablas++;
           }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex, "Error al Cargar Grilla 1, Posible Error de Conxion con la BD"+ex.getMessage(), JOptionPane.ERROR_MESSAGE);
        }      
        jTextField2.setText(String.valueOf(tablas));
        jTextField3.setText(String.valueOf(cantidad));
    }
    
    public void Migracion(){
            for (String cancion : canciones) {
                switch(cancion){
                    case"BALGRAL":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.BALGRAL\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.BALGRAL (BalGralId,BalGralUsr,BalGralCtaMh)\n" +
                            "select BalGralId,BalGralUsr,BalGralCtaMh from "+Conexion.conexionorivar+".dbo.BALGRAL");
                            psql.execute();
                            psql.close();                            
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en BALGRAL "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }
                    break;
                    case"AJUSTECAMBIO":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.AJUSTECAMBIO\n" +
                            "SET IDENTITY_INSERT AJUSTECAMBIO ON\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.AJUSTECAMBIO (AjuCamId,AjuCamEmp,AjuCamUsr,AjuCamFec,SucId,SucEmp,CtaId,CtaEmp,MonId,MonEmp,AjuCamTipCue,AjuCamDet,AjuCamTipCam,AjuCamNroAsn)\n" +
                            "select AjuCamId,AjuCamEmp,AjuCamUsr,AjuCamFec,SucId,SucEmp,CtaId,CtaEmp,MonId,MonEmp,AjuCamTipCue,AjuCamDet,AjuCamTipCam,AjuCamNroAsn from "+Conexion.conexionorivar+".dbo.AJUSTECAMBIO\n" +
                            "SET IDENTITY_INSERT AJUSTECAMBIO  OFF");
                            psql.execute();
                            psql.close();   
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en AJUSTECAMBIO "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }               
                    break;
                    case"BDAUXILIARESSALARIO":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.BDAUXILIARESSALARIO\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.BDAUXILIARESSALARIO (bdAuxiliaresSalarioId, bdAuxiliaresSalarioImp)\n" +
                            "select bdAuxiliaresSalarioId, bdAuxiliaresSalarioImp from "+Conexion.conexionorivar+".dbo.BDAUXILIARESSALARIO");
                            psql.execute();
                            psql.close();                                   
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en AJUSTECAMBIO "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }
                    break;
                    case"BDBALANCEVERIF":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.BDBALANCEVERIF\n" +
                            "SET IDENTITY_INSERT BDBALANCEVERIF ON\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.BDBALANCEVERIF (bdBalanceVerifId,bdBalanceVerifFecha,bdBalanceVerifEmpId,bdBalanceVerifUsrId,bdBalanceVerifObs)\n" +
                            "select bdBalanceVerifId,bdBalanceVerifFecha,bdBalanceVerifEmpId,bdBalanceVerifUsrId,bdBalanceVerifObs from "+Conexion.conexionorivar+".dbo.BDBALANCEVERIF\n" +
                            "SET IDENTITY_INSERT BDBALANCEVERIF OFF");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en BDBALANCEVERIF "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }
                    break;
                    case"BDCOBRO":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.BDCOBRO\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.BDCOBRO (bdCobroId,bdCobroIte,bdCobroFec,bdCobroNroRec,bdCobroRuc,bdCobroNom,bdCobroServ,bdCobroImp,bdCobroOri,bdCobroOriId,bdCobroMes,bdCobroUsr,bdCobroEmp,bdCobroRetImp,bdCobroAntiImp,bdCobroFacId,bdCobroFacIte,bdCobroAnl)\n" +
                            "select bdCobroId,bdCobroIte,bdCobroFec,bdCobroNroRec,bdCobroRuc,bdCobroNom,bdCobroServ,bdCobroImp,bdCobroOri,bdCobroOriId,bdCobroMes,bdCobroUsr,bdCobroEmp,bdCobroRetImp,bdCobroAntiImp,bdCobroFacId,bdCobroFacIte,bdCobroAnl from "+Conexion.conexionorivar+".dbo.BDCOBRO");                              
                            psql.execute();
                            psql.close();                                                
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en BDCOBRO "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }
                    break;     
                    case"BDCONFIGURACION":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.BDCONFIGURACION\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.BDCONFIGURACION (BdConfiguracionId,BdConfiguracionVenc,BdConfiguracionCump,BdConfiguracionSoli,BdConfiguracionNoFac,BdConfiguracionNota,BdConfiguracionTimFac,BdConfiguracionTimNot,BdConfiguracionCostoOp,BdConfiguracionVencObli)\n" +
                            "select BdConfiguracionId,BdConfiguracionVenc,BdConfiguracionCump,BdConfiguracionSoli,BdConfiguracionNoFac,BdConfiguracionNota,BdConfiguracionTimFac,BdConfiguracionTimNot,BdConfiguracionCostoOp,BdConfiguracionVencObli FROM "+Conexion.conexionorivar+".dbo.BDCONFIGURACION ");                              
                            psql.execute();
                            psql.close();                                                
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en BDCONFIGURACION "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                       
                    break;
                    case"BDDOCUMENTOS":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.BDDOCUMENTOS\n" +
                            "SET IDENTITY_INSERT BDDOCUMENTOS ON\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.BDDOCUMENTOS (bdDocumentosId,bdDocumentosDoc,bdDocumentosEst,bdDocumentosFec,bdDocumentosSol,bdDocumentosUsrId,bdDocumentosDev,bdDocumentosEmpId,bdDocumentosRef,bdDocumentosFecSol,bdDocumentosFecRec,bdDocumentosFecDev)\n" +
                            "select bdDocumentosId,bdDocumentosDoc,bdDocumentosEst,bdDocumentosFec,bdDocumentosSol,bdDocumentosUsrId,bdDocumentosDev,bdDocumentosEmpId,bdDocumentosRef,bdDocumentosFecSol,bdDocumentosFecRec,bdDocumentosFecDev from "+Conexion.conexionorivar+".dbo.BDDOCUMENTOS\n" +
                            "SET IDENTITY_INSERT BDDOCUMENTOS OFF");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en BDDOCUMENTOS "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                          
                    break;
                    case"BDDOCUMENTOSCAB":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.BDDOCUMENTOSCAB\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.BDDOCUMENTOSCAB (bdDocumentosCabId,bdDocumentosCabEmp,bdDocumentosCabFecha,bdDocumentosCabDoc,bdDocumentosCabUsrId)\n" +
                            "select bdDocumentosCabId,bdDocumentosCabEmp,bdDocumentosCabFecha,bdDocumentosCabDoc,bdDocumentosCabUsrId FROM "+Conexion.conexionorivar+".dbo.BDDOCUMENTOSCAB ");                              
                            psql.execute();
                            psql.close();                                                
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en BDDOCUMENTOSCAB "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                         
                    break;
                    case"BDFACTURA":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.BDFACTURA\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.BDFACTURA (bdFacturaId,bdFacturaIte,bdFacturaFec,bdFacturaNoFac,bdFacturaTim,bdFacturaRuc,bdFacturaCliNom,bdFacturaForPag,bdFacturaTipCmp,bdFacturaServ,bdFacturaPrecio,bdFacturaOri,bdFacturaOriId,bdFacturaMes,bdFacturaUsr,bdFacturaEmp)\n" +
                            "select bdFacturaId,bdFacturaIte,bdFacturaFec,bdFacturaNoFac,bdFacturaTim,bdFacturaRuc,bdFacturaCliNom,bdFacturaForPag,bdFacturaTipCmp,bdFacturaServ,bdFacturaPrecio,bdFacturaOri,bdFacturaOriId,bdFacturaMes,bdFacturaUsr,bdFacturaEmp FROM "+Conexion.conexionorivar+".dbo.BDFACTURA ");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en BDFACTURA "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }
                    break;
                    case"BDGENCOBRO":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.BDGENCOBRO\n" +
                            "SET IDENTITY_INSERT BDGENCOBRO ON\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.BDGENCOBRO (bdGenCobroId,bdGenCobroEmp,bdGenCobroServ,bdGenCobroOri,bdGenCobroOriId,bdGenCobroFacId,bdGenCobroFacIte,bdGenCobroImp,bdGenCobroAju,bdGenCobroId2,bdGenCobroUsr,bdGenCobroMes,bdGenCobroImpNc)\n" +
                            "select bdGenCobroId,bdGenCobroEmp,bdGenCobroServ,bdGenCobroOri,bdGenCobroOriId,bdGenCobroFacId,bdGenCobroFacIte,bdGenCobroImp,bdGenCobroAju,bdGenCobroId2,bdGenCobroUsr,bdGenCobroMes,bdGenCobroImpNc from "+Conexion.conexionorivar+".dbo.BDGENCOBRO\n" +
                            "SET IDENTITY_INSERT BDGENCOBRO OFF");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en BDGENCOBRO "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                         
                    break;
                    case"BDGENFACTURA":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.BDGENFACTURA\n" +
                            "SET IDENTITY_INSERT BDGENFACTURA ON\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.BDGENFACTURA (bdGenFacturaId,bdGenFacturaServ,bdGenFacturaPre,bdGenFacturaOri,bdGenFacturaOriId,bdGenFacturaFec,bdGenFacturaM,bdGenFacturaUsr,bdGenFacturaImpNc)\n" +
                            "select bdGenFacturaId,bdGenFacturaServ,bdGenFacturaPre,bdGenFacturaOri,bdGenFacturaOriId,bdGenFacturaFec,bdGenFacturaM,bdGenFacturaUsr,bdGenFacturaImpNc from "+Conexion.conexionorivar+".dbo.BDGENFACTURA\n" +
                            "SET IDENTITY_INSERT BDGENFACTURA OFF");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en BDGENFACTURA "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                           
                    break;
                    case"BDHONOPROF":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.BDHONOPROF\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.BDHONOPROF (bdHonoProfFec,bdHonoProfEmpId,bdHonoProfImporte)\n" +
                            "select bdHonoProfFec,bdHonoProfEmpId,bdHonoProfImporte FROM "+Conexion.conexionorivar+".dbo.BDHONOPROF ");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en BDHONOPROF "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                        
                    break;
                    case"BDMESAJEH":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.BDMESAJEH\n" +
                            "SET IDENTITY_INSERT BDMESAJEH ON\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.BDMESAJEH (BdMesajeHId,BdMesajeHUsr,BdMesajeHUsrNom,BdMesajeHUsrEmi,BdMesajeHEmisor,BdMesajeHTxt,BdMesajeHFec,BdMesajeHHora)\n" +
                            "select BdMesajeHId,BdMesajeHUsr,BdMesajeHUsrNom,BdMesajeHUsrEmi,BdMesajeHEmisor,BdMesajeHTxt,BdMesajeHFec,BdMesajeHHora from "+Conexion.conexionorivar+".dbo.BDMESAJEH\n" +
                            "SET IDENTITY_INSERT BDMESAJEH OFF");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en BDMESAJEH "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                        
                    break;
                    case"BDMESAJEHLEVEL1":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.BDMESAJEHLEVEL1\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.BDMESAJEHLEVEL1 (BdMesajeHId,BdMesajeHIte,BdMesajeHLevelFec,BdMesajeHLevelHora)\n" +
                            "select BdMesajeHId,BdMesajeHIte,BdMesajeHLevelFec,BdMesajeHLevelHora FROM "+Conexion.conexionorivar+".dbo.BDMESAJEHLEVEL1 ");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en BDMESAJEHLEVEL1 "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                        
                    break;
                    case"BDOBLIGACIONES":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.BDOBLIGACIONES\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.BDOBLIGACIONES (bdObligacionesId,bdObligacionesDesc,bdObligacionesCantVenc,bdObligacionesMesVen,bdObligacionesImp,bdObligacionesRang,bdObligacionesImpAux,bdObligacionesMulta)\n" +
                            "select bdObligacionesId,bdObligacionesDesc,bdObligacionesCantVenc,bdObligacionesMesVen,bdObligacionesImp,bdObligacionesRang,bdObligacionesImpAux,bdObligacionesMulta FROM "+Conexion.conexionorivar+".dbo.BDOBLIGACIONES ");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en BDOBLIGACIONES "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                        
                    break;
                    case"BDOBLIGACIONES2":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.BDOBLIGACIONES2\n" +
                            "SET IDENTITY_INSERT BDOBLIGACIONES2 ON\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.BDOBLIGACIONES2 (BdObligaciones2Id,BdObligaciones2Emp,BdObligaciones2OblId,BdObligaciones2Imp)\n" +
                            "select BdObligaciones2Id,BdObligaciones2Emp,BdObligaciones2OblId,BdObligaciones2Imp from "+Conexion.conexionorivar+".dbo.BDOBLIGACIONES2\n" +
                            "SET IDENTITY_INSERT BDOBLIGACIONES2 OFF");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en BDOBLIGACIONES2 "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                         
                    break;   
                    case"BDOBLIGACIONESDET":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.BDOBLIGACIONESDET\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.BDOBLIGACIONESDET (bdObligacionesDetId,bdObligacionesDetIte,bdObligacionesDetComIni,bdObligacionesDetComFin,bdObligacionesDetVenIni,bdObligacionesDetVenFin,bdObligacionesDetImp)\n" +
                            "select bdObligacionesDetId,bdObligacionesDetIte,bdObligacionesDetComIni,bdObligacionesDetComFin,bdObligacionesDetVenIni,bdObligacionesDetVenFin,bdObligacionesDetImp FROM "+Conexion.conexionorivar+".dbo.BDOBLIGACIONESDET ");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en BDOBLIGACIONESDET "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                          
                    break;
                    case"BDPRESOBLI":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.BDPRESOBLI\n" +
                            "SET IDENTITY_INSERT BDPRESOBLI ON\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.BDPRESOBLI (bdPresObliId,bdPresObliEmp,bdPresObliCod,bdPresObliMes,bdPresObliFec,bdPresObliMulta)\n" +
                            "select bdPresObliId,bdPresObliEmp,bdPresObliCod,bdPresObliMes,bdPresObliFec,bdPresObliMulta from "+Conexion.conexionorivar+".dbo.BDPRESOBLI\n" +
                            "SET IDENTITY_INSERT BDPRESOBLI OFF");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en BDPRESOBLI "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                          
                    break;
                    case"BDREMBOLSO":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.BDREMBOLSO\n" +
                            "SET IDENTITY_INSERT BDREMBOLSO ON\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.BDREMBOLSO (bdRembolsoId,bdRembolsoRefe,bdRembolsoEmpId,bdRembolsoUsrId,bdRembolsoFec,bdRembolsoEstado,bdRembolsoFecFin)\n" +
                            "select bdRembolsoId,bdRembolsoRefe,bdRembolsoEmpId,bdRembolsoUsrId,bdRembolsoFec,bdRembolsoEstado,bdRembolsoFecFin from "+Conexion.conexionorivar+".dbo.BDREMBOLSO\n" +
                            "SET IDENTITY_INSERT BDREMBOLSO OFF");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en BDREMBOLSO "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                          
                    break;
                    case"BDREMBOLSODET":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.BDREMBOLSODET\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.BDREMBOLSODET (bdRembolsoDetId,bdRembolsoDetIte,bdRembolsoDetDesc,bdRembolsoDetDoc,bdRembolsoDetFec,bdRembolsoDetTot,bdRembolsoDetGra10,bdRembolsoDetIva10,bdRembolsoDetGra05,bdRembolsoDetIva05,bdRembolsoDetExe,bdRembolsoDetEst,bdRembolsoDetPagId,bdRembolsoDetOtr)\n" +
                            "select bdRembolsoDetId,bdRembolsoDetIte,bdRembolsoDetDesc,bdRembolsoDetDoc,bdRembolsoDetFec,bdRembolsoDetTot,bdRembolsoDetGra10,bdRembolsoDetIva10,bdRembolsoDetGra05,bdRembolsoDetIva05,bdRembolsoDetExe,bdRembolsoDetEst,bdRembolsoDetPagId,bdRembolsoDetOtr FROM "+Conexion.conexionorivar+".dbo.BDREMBOLSODET ");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en BDREMBOLSODET "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                              
                    break;
                    case"BDSERVICIOS":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.BDSERVICIOS\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.BDSERVICIOS (bdServiciosId,bdServiciosDesc,bdServiciosImp)\n" +
                            "select bdServiciosId,bdServiciosDesc,bdServiciosImp FROM "+Conexion.conexionorivar+".dbo.BDSERVICIOS ");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en BDSERVICIOS "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                        
                    break;
                    case"BDSERVVARIOS":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.BDSERVVARIOS\n" +
                            "SET IDENTITY_INSERT BDSERVVARIOS ON\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.BDSERVVARIOS (bdServVariosId,bdServVariosEmpId,bdServiciosId,bdServVariosImp,bdServVariosFecSol,bdServVariosFecEnt,bdServVariosEst)\n" +
                            "select bdServVariosId,bdServVariosEmpId,bdServiciosId,bdServVariosImp,bdServVariosFecSol,bdServVariosFecEnt,bdServVariosEst from "+Conexion.conexionorivar+".dbo.BDSERVVARIOS\n" +
                            "SET IDENTITY_INSERT BDSERVVARIOS OFF");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en BDSERVVARIOS "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                             
                    break;
                    case"BDTAREAS":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.BDTAREAS\n" +
                            "SET IDENTITY_INSERT BDTAREAS ON\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.BDTAREAS (bdTareasId,bdTareasEmp,bdTareasFec,bdTareasDet,bdTareasHora,bdTareasUsr,bdTareasCarPor,bdTareasOri,bdTareasIdOri,bdTareasEstado,bdTareasFecFin)\n" +
                            "select bdTareasId,bdTareasEmp,bdTareasFec,bdTareasDet,bdTareasHora,bdTareasUsr,bdTareasCarPor,bdTareasOri,bdTareasIdOri,bdTareasEstado,bdTareasFecFin from "+Conexion.conexionorivar+".dbo.BDTAREAS\n" +
                            "SET IDENTITY_INSERT BDTAREAS OFF");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en BDTAREAS "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                         
                    break;
                    case"BDTAREASVARIAS":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.BDTAREASVARIAS\n" +
                            "SET IDENTITY_INSERT BDTAREASVARIAS ON\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.BDTAREASVARIAS (bdTareasVariasID,bdTareasVariasEmp,bdTareasVariasUsr,bdTareasVariasResp,bdTareasVariasDesc,bdTareasVariasFec,bdTareasVariasHora,bdTareasVariasEst,bdTareasVariasVisto)\n" +
                            "select bdTareasVariasID,bdTareasVariasEmp,bdTareasVariasUsr,bdTareasVariasResp,bdTareasVariasDesc,bdTareasVariasFec,bdTareasVariasHora,bdTareasVariasEst,bdTareasVariasVisto from "+Conexion.conexionorivar+".dbo.BDTAREASVARIAS\n" +
                            "SET IDENTITY_INSERT BDTAREASVARIAS OFF");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en BDTAREASVARIAS "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                           
                    break;
                    case"BDTIMBAJA":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.BDTIMBAJA\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.BDTIMBAJA (BdTimBajaEmp,BdTimBajaNro,BdTimBajaFec,BdTimBajaUsr)\n" +
                            "select BdTimBajaEmp,BdTimBajaNro,BdTimBajaFec,BdTimBajaUsr FROM "+Conexion.conexionorivar+".dbo.BDTIMBAJA ");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en BDTIMBAJA "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                        
                    break;
                    case"BDUSUASIG":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.BDUSUASIG\n" +
                            "SET IDENTITY_INSERT BDUSUASIG ON\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.BDUSUASIG (bdUsuAsigId,bdUsuAsigUsrId,bdUsuAsigEmpId)\n" +
                            "select bdUsuAsigId,bdUsuAsigUsrId,bdUsuAsigEmpId from "+Conexion.conexionorivar+".dbo.BDUSUASIG\n" +
                            "SET IDENTITY_INSERT BDUSUASIG OFF");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en BDUSUASIG "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                        
                    break;
                    case"BDUSUULTMSG":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.BDUSUULTMSG\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.BDUSUULTMSG (bdUsuUltMsgUsr,bdUsuUltMsgLinea)\n" +
                            "select bdUsuUltMsgUsr,bdUsuUltMsgLinea FROM "+Conexion.conexionorivar+".dbo.BDUSUULTMSG ");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en BDUSUULTMSG "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                        
                    break;
                    case"BDVISITA":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.BDVISITA\n" +
                            "SET IDENTITY_INSERT BDVISITA ON\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.BDVISITA (bdVisitaId,bdVisitaEmpId,bdVisitaFec,bdVisitaHora,bdVisitaResp,bdVisitaUsrId,bdVisitaObs,bdVisitaProgId)\n" +
                            "select bdVisitaId,bdVisitaEmpId,bdVisitaFec,bdVisitaHora,bdVisitaResp,bdVisitaUsrId,bdVisitaObs,bdVisitaProgId from "+Conexion.conexionorivar+".dbo.BDVISITA\n" +
                            "SET IDENTITY_INSERT BDVISITA OFF");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en BDVISITA "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                         
                    break;
                    case"BDVISITASPROG":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.BDVISITASPROG\n" +
                            "SET IDENTITY_INSERT BDVISITASPROG ON\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.BDVISITASPROG (bdVisitasProgId,bdVisitasProgEmpId,bdVisitasProgResp,bdVisitasProgUsrId,bdVisitasProgFec,bdVisitasProgPorS,bdVisitasProgPorM,bdVisitasProgDo,bdVisitasProgHoraDo,bdVisitasProgLu,bdVisitasProgHoraLu,bdVisitasProgMa,bdVisitasProgHoraMa,bdVisitasProgMi,bdVisitasProgHoraMi,bdVisitasProgJu,bdVisitasProgHoraJu,bdVisitasProgVi,bdVisitasProgHoraVi,bdVisitasProgSa,bdVisitasProgHoraSa,bdVisitasProgCadaS,bdVisitasProgCadaD,bdVisitasProgVisitaM,bdVisitasProgPrimSem,bdVisitasProgHora)\n" +
                            "select bdVisitasProgId,bdVisitasProgEmpId,bdVisitasProgResp,bdVisitasProgUsrId,bdVisitasProgFec,bdVisitasProgPorS,bdVisitasProgPorM,bdVisitasProgDo,bdVisitasProgHoraDo,bdVisitasProgLu,bdVisitasProgHoraLu,bdVisitasProgMa,bdVisitasProgHoraMa,bdVisitasProgMi,bdVisitasProgHoraMi,bdVisitasProgJu,bdVisitasProgHoraJu,bdVisitasProgVi,bdVisitasProgHoraVi,bdVisitasProgSa,bdVisitasProgHoraSa,bdVisitasProgCadaS,bdVisitasProgCadaD,bdVisitasProgVisitaM,bdVisitasProgPrimSem,bdVisitasProgHora from "+Conexion.conexionorivar+".dbo.BDVISITASPROG\n" +
                            "SET IDENTITY_INSERT BDVISITA OFF");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en BDVISITASPROG "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                        
                    break;
                    case"CANCUORET":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.CANCUORET\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.CANCUORET (CanCuoRetId,CanCuoRetEmp,CanCuoRetLin,CanCuoRetFec,CanCuoRetTimbra,CanCuoRetNroCmp,CanCuoRetImpIva,CanCuoRetImpMeIva,CanCuoRetImpRen,CanCuoRetImpMeRen,CanCuoRetImpLey,CanCuoRetImpMeLey,CanCuoRetCuotaId,CanCuoRetRucComId,CanCuoRetIvaConcepto,CanCuoRetRenConcepto,CanCuoRetImpIva05,CanCuoRetImpMeIva05,CanCuoRetPorRet05,CanCuoRetPorRet10)\n" +
                            "select CanCuoRetId,CanCuoRetEmp,CanCuoRetLin,CanCuoRetFec,CanCuoRetTimbra,CanCuoRetNroCmp,CanCuoRetImpIva,CanCuoRetImpMeIva,CanCuoRetImpRen,CanCuoRetImpMeRen,CanCuoRetImpLey,CanCuoRetImpMeLey,CanCuoRetCuotaId,CanCuoRetRucComId,CanCuoRetIvaConcepto,CanCuoRetRenConcepto,CanCuoRetImpIva05,CanCuoRetImpMeIva05,CanCuoRetPorRet05,CanCuoRetPorRet10 FROM "+Conexion.conexionorivar+".dbo.CANCUORET ");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en CANCUORET "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                        
                    break;
                    case"CHEQUERA":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.CHEQUERA\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.CHEQUERA (CheqId,CheqEmp,CheqNom,CheqFec,CheqRep,CheqUsr,CheqLinea)\n" +
                            "select CheqId,CheqEmp,CheqNom,CheqFec,CheqRep,CheqUsr,CheqLinea FROM "+Conexion.conexionorivar+".dbo.CHEQUERA ");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en CHEQUERA "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                         
                    break;
                    case"CNFRUCOM":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.CNFRUCOM\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.CNFRUCOM (CnfRucComId,CnfRucComCnt,CnfRucComCntME,CnfRucComCre,CnfRucComOrd,CnfRucComNoGen,CnfRucComGenxCmp,CnfRucComGenDes,CnfRucComPagFin,CnfRucComNoGenOrd,CnfRucComOmi,CnfRucComPer,CnfRucComAvi,CnfRucComUsr,CnfRucComFmt,CnfRucComCta05,CnfRucComCta10,CnfRucComDes,CnfRucComDev,CnfRucComAntMl,CnfRucComAntME,CnfRucComTsaka,CnfRucComIvaGto10,CnfRucComIvaGto05)\n" +
                            "select CnfRucComId,CnfRucComCnt,CnfRucComCntME,CnfRucComCre,CnfRucComOrd,CnfRucComNoGen,CnfRucComGenxCmp,CnfRucComGenDes,CnfRucComPagFin,CnfRucComNoGenOrd,CnfRucComOmi,CnfRucComPer,CnfRucComAvi,CnfRucComUsr,CnfRucComFmt,CnfRucComCta05,CnfRucComCta10,CnfRucComDes,CnfRucComDev,CnfRucComAntMl,CnfRucComAntME,CnfRucComTsaka,CnfRucComIvaGto,CnfRucComIvaGto05 FROM "+Conexion.conexionorivar+".dbo.CNFRUCOM ");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en CNFRUCOM "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);
                        }
                    break;
                    case"CNFRUCVEN":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.CNFRUCVEN\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.CNFRUCVEN (CnfRucVenId,CnfRucConCaj,CnfRucConGra,CnfRucConExe,CnfRucCreCli,CnfRucCreGra,CnfRucCreExe,CnfRucTicCon,CnfRucTicCre,CnfRucTicNotCre,CnfRucTicNotDeb,CnfRucTicCta,CnfRucTic,CnfRucUtTic,CnfRucHabCta,CnfRucOmiCon,CnfRucGenAst,CnfRucMosAst,CnfRucAvi,CnfRucUsr,CnfRucTicFac,CnfRucconGra10,CnfRucCreGra10,CnfRucNotCreDev,CnfRucNotCreDes,CnfRucVenIva10,CnfRucVenIva05,CnfRucConMe,cnfrucretley,cnfrucventim,CnfRucVenCobroFin,CnfRucVenRet2051)\n" +
                            "select CnfRucVenId,CnfRucConCaj,CnfRucConGra,CnfRucConExe,CnfRucCreCli,CnfRucCreGra,CnfRucCreExe,CnfRucTicCon,CnfRucTicCre,CnfRucTicNotCre,CnfRucTicNotDeb,CnfRucTicCta,CnfRucTic,CnfRucUtTic,CnfRucHabCta,CnfRucOmiCon,CnfRucGenAst,CnfRucMosAst,CnfRucAvi,CnfRucUsr,CnfRucTicFac,CnfRucconGra10,CnfRucCreGra10,CnfRucNotCreDev,CnfRucNotCreDes,CnfRucVenIva10,CnfRucVenIva05,CnfRucConMe,cnfrucretley,cnfrucventim,CnfRucVenCobroFin,CnfRucRet2051 FROM "+Conexion.conexionorivar+".dbo.CNFRUCVEN");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en CNFRUCVEN "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }
                    break;
                    case"COEFICIENTE":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.COEFICIENTE\n" +
                            "SET IDENTITY_INSERT COEFICIENTE ON\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.COEFICIENTE (CoeId,Coefec,CoeCom,CoeEna,CoeEmp,CoeUsr)\n" +
                            "select CoeId,Coefec,CoeCom,CoeEna,CoeEmp,CoeUsr from "+Conexion.conexionorivar+".dbo.COEFICIENTE\n" +
                            "SET IDENTITY_INSERT COEFICIENTE OFF");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en COEFICIENTE "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }
                    break;
                    case"COMEXPORT":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.COMEXPORT\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.COMEXPORT (ComExportId,ComExport100,ComExport101,ComExport102,ComExport103,ComExport104,ComExport105,ComExport106,ComExport107,ComExport108,ComExport109,ComExport110,ComExport111,ComExport112,ComExport113,ComExport114,ComExport115,ComExport116,ComExport117,ComExport118,ComExport119,ComExport120,ComExport121,ComExport122,ComExport123,ComExport124,ComExport125,ComExport126,ComExport127,ComExport128,ComExport129,ComExport130,ComExport131,ComExport132,ComExport133,ComExport134,ComExport135)\n" +
                            "select ComExportId,ComExport100,ComExport101,ComExport102,ComExport103,ComExport104,ComExport105,ComExport106,ComExport107,ComExport108,ComExport109,ComExport110,ComExport111,ComExport112,ComExport113,ComExport114,ComExport115,ComExport116,ComExport117,ComExport118,ComExport119,ComExport120,ComExport121,ComExport122,ComExport123,ComExport124,ComExport125,ComExport126,ComExport127,ComExport128,ComExport129,ComExport130,ComExport131,ComExport132,ComExport133,ComExport134,ComExport135 FROM "+Conexion.conexionorivar+".dbo.COMEXPORT");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en COMEXPORT "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }
                    break;
                    case"CONCEPTO":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.CONCEPTO\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.CONCEPTO (ConNom,ConEmp,ConUsr)\n" +
                            "select ConNom,ConEmp,ConUsr FROM "+Conexion.conexionorivar+".dbo.CONCEPTO");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en CONCEPTO "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                        
                    break;
                    case"CONFREV":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.CONFREV\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.CONFREV (ConfEmp,ConfCtaResRev,ConfCtaAcu,ConCtaDepEje,ConCtaDepEjeGND)\n" +
                            "select ConfEmp,ConfCtaResRev,ConfCtaAcu,ConCtaDepEje,ConCtaDepEjeGND FROM "+Conexion.conexionorivar+".dbo.CONFREV");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en CONCEPTO "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                        
                    break;
                    case"CUENTAMHR110":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.CUENTAMHR110\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.CUENTAMHR110 (CtaMhR110Emp,CtaMhR110Id,CtaMhR110Usr,CtaMhR110Nom,CtaMhR110Nat,CtaMhR110Niv,CtaMhR110Ast,CtaMhR110EjAct,CtaMhR110EjAnt,CtaMhR110Res,CtaMhR110Ord)\n" +
                            "select CtaMhR110Emp,CtaMhR110Id,CtaMhR110Usr,CtaMhR110Nom,CtaMhR110Nat,CtaMhR110Niv,CtaMhR110Ast,CtaMhR110EjAct,CtaMhR110EjAnt,CtaMhR110Res,CtaMhR110Ord FROM "+Conexion.conexionorivar+".dbo.CUENTAMHR110");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en CUENTAMHR110 "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                             
                    break;
                    case"DETTESAKA":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.DETTESAKA\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.DETTESAKA (DetTesakaIte,DetTesakaRuc,DetTesakaNroFac,DetTesakaTim,DetTesakaFec,DetTesakaTipCmp,DetTesakaEmp,DetTesakaDesc,DetTesakaCant,DetTesakaCosto,DetTesakaTasa)\n" +
                            "select DetTesakaIte,DetTesakaRuc,DetTesakaNroFac,DetTesakaTim,DetTesakaFec,DetTesakaTipCmp,DetTesakaEmp,DetTesakaDesc,DetTesakaCant,DetTesakaCosto,DetTesakaTasa FROM "+Conexion.conexionorivar+".dbo.DETTESAKA");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en DETTESAKA "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                          
                    break;
                    case"FORMATO":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.FORMATO\n" +
                            "SET IDENTITY_INSERT FORMATO ON\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.FORMATO (FormatId,FormatCod,FormatNom,FormatRep,FormatEmp,FormatUsr,FormatFecVen)\n" +
                            "select FormatId,FormatCod,FormatNom,FormatRep,FormatEmp,FormatUsr,FormatFecVen FROM "+Conexion.conexionorivar+".dbo.FORMATO\n" +
                            "SET IDENTITY_INSERT FORMATO OFF");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en FORMATO "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                         
                    break;
                    case"FORMATOV":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.TIMCLIENTE\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.TIMCLIENTE (TimCliUsr,TimCliTim,TimCliSuc,TimCliEmp,TimCliFecVen,TimCliente,TimCliTipCmp,TimCliNroFin,TimCliNroIni,TimCliCaja,TimCliFecIni)\n" +
                            "select FormatvUsr,FormatVCod,FormatVRep,FormatVEmp,FormatVFecVen,0,13,'','','','17530101' from "+Conexion.conexionorivar+".dbo.FORMATOV");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en TIMCLIENTE "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                                                
                    break;
                    case"NIVELES":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.NIVELES\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.NIVELES (NivId,NivNom,NivModCmp,NivPerPag)\n" +
                            "select NivId,NivNom,0,0 from "+Conexion.conexionorivar+".dbo.NIVELES");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en NIVELES "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                        
                    break;
                    case"PAGO":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.PAGO\n" +
                            "SET IDENTITY_INSERT PAGO ON\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.PAGO (PagId,PrvId,PrvEmp,PagSuc,PagTip,PagEmp,PagUsr,PagNroRec,PagNroOrd,PagFec,PagFecVen,PagBan,BanId,BanEmp,PagAfcCnt,PagNroChq,PagBen,PagCenCos,PagTipFac,PagNroFac,PagNroAst,PagCam,PagImp,PagImpMl,PagCon,PagRetIva,PagRetRen,PagRet2051,PagRetNet,PagNoRet)\n" +
                            "select PagId,PrvId,PrvEmp,PagSuc,PagTip,PagEmp,PagUsr,PagNroRec,PagNroOrd,PagFec,PagFecVen,PagBan,BanId,BanEmp,PagAfcCnt,PagNroChq,PagBen,PagCenCos,PagTipFac,PagNroFac,PagNroAst,PagCam,PagImp,PagImpMl,SubString(PagCon,0,80),PagRetIva,PagRetRen,PagRet2051,PagRetNet,PagNoRet FROM "+Conexion.conexionorivar+".dbo.PAGO\n" +
                            "SET IDENTITY_INSERT PAGO OFF");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en PAGO "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                        
                    break;
                    case"PERMISO":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.PERMISO\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.PERMISO (PrmEmpId,PrmUsrId)\n" +
                            "select PrmEmpId,PrmUsrId from "+Conexion.conexionorivar+".dbo.PERMISO");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en PERMISO "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                        
                    break;
                    case"PRESENTACION":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.PRESENTACION\n" +
                            "SET IDENTITY_INSERT PRESENTACION ON\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.PRESENTACION (PresentacionId,PresentacionEmp,PresentacionMes,Presentaciondia)\n" +
                            "select PresentacionId,PresentacionEmp,PresentacionMes,Presentaciondia FROM "+Conexion.conexionorivar+".dbo.PRESENTACION\n" +
                            "SET IDENTITY_INSERT PRESENTACION OFF");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en PRESENTACION "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                         
                    break;
                    case"PRESUPUESTO":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.PRESUPUESTO\n" +
                            "SET IDENTITY_INSERT PRESUPUESTO ON\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.PRESUPUESTO (PreId,SucId,SucEmp,PreDes,PreCen,PreEmp,PreUsr,PreFec,CtaId,CtaEmp,PreCam,PreVal,PreImp,PreEje)\n" +
                            "select PreId,SucId,SucEmp,PreDes,PreCen,PreEmp,PreUsr,PreFec,CtaId,CtaEmp,PreCam,PreVal,PreImp,PreEje FROM "+Conexion.conexionorivar+".dbo.PRESUPUESTO\n" +
                            "SET IDENTITY_INSERT PRESUPUESTO OFF");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en PRESUPUESTO "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                         
                    break;
                    case"RECTIFICATIVA":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.RECTIFICATIVA\n" +
                            "SET IDENTITY_INSERT RECTIFICATIVA ON\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.RECTIFICATIVA (RectificativaId,RectificativaEmp,RectificativaRuc,RectificativaRaz,RectificativaNoFac,RectificativaNoRet,RectificativaTim,RectificativaTipCmp,RectificativaFecFac,RectificativaFecRet,RectificativaGra10,RectificativaIva10,RectificativaGra05,RectificativaIva05,RectificativaExe,RectificativaTot,RectificativaBasRen,RectificativaRetRen,RectificativaBasIva,RectificativaRetIva,RectificativaTipo,RectificativaMotivo,RectificativaDescrip,RectificativaNroCas,RectificativaRucId,RectificativaFecFacV,RectificativaGra10V,RectificativaIva10V,RectificativaGra05V,RectificativaIva05V,RectificativaExeV,RectificativaTotV,RectificativaBasRenV,RectificativaRetRenV,RectificativaBasIvaV,RectificativaRetIvaV,RectificativaRub10,RectificativaRub10V,RectificativaIn10,RectificativaIn10V,RectificativaRub05,RectificativaRub05V,RectificativaIn05,RectificativaIn05V,RectificativaRub,RectificativaRubV,RectificativaIn,RectificativaInV,RectificativaOri,RectificativaOriId)\n" +
                            "select RectificativaId,RectificativaEmp,RectificativaRuc,RectificativaRaz,RectificativaNoFac,RectificativaNoRet,RectificativaTim,RectificativaTipCmp,RectificativaFecFac,RectificativaFecRet,RectificativaGra10,RectificativaIva10,RectificativaGra05,RectificativaIva05,RectificativaExe,RectificativaTot,RectificativaBasRen,RectificativaRetRen,RectificativaBasIva,RectificativaRetIva,RectificativaTipo,RectificativaMotivo,RectificativaDescrip,RectificativaNroCas,RectificativaRucId,RectificativaFecFacV,RectificativaGra10V,RectificativaIva10V,RectificativaGra05V,RectificativaIva05V,RectificativaExeV,RectificativaTotV,RectificativaBasRenV,RectificativaRetRenV,RectificativaBasIvaV,RectificativaRetIvaV,RectificativaRub10,RectificativaRub10V,RectificativaIn10,RectificativaIn10V,RectificativaRub05,RectificativaRub05V,RectificativaIn05,RectificativaIn05V,RectificativaRub,RectificativaRubV,RectificativaIn,RectificativaInV,RectificativaOri,RectificativaOriId FROM "+Conexion.conexionorivar+".dbo.RECTIFICATIVA\n" +
                            "SET IDENTITY_INSERT RECTIFICATIVA OFF");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en RECTIFICATIVA "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                           
                    break;
                    case"RESPONSABLE":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.RESPONSABLE\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.RESPONSABLE (RspId,RspEmp,RspDen,RspNom,RspTel,RspUltNro,RspCta,CtaId,CtaEmp,RspMon,RspUsr,RspSalIni)\n" +
                            "select RspId,RspEmp,RspDen,RspNom,RspTel,RspUltNro,RspCta,CtaId,CtaEmp,RspMon,RspUsr,0 from "+Conexion.conexionorivar+".dbo.RESPONSABLE");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en RESPONSABLE "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                         
                    break;
                    case"RESPONSABLELEVEL1":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.RESPONSABLELEVEL1\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.RESPONSABLELEVEL1 (RspId,RspEmp,RspNroLin,RspNombre,RspTelef)\n" +
                            "select RspId,RspEmp,RspNroLin,RspNombre,RspTelef from "+Conexion.conexionorivar+".dbo.RESPONSABLELEVEL1");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en RESPONSABLELEVEL1 "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }
                    break;
                    case"RETENCION":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.RETENCION\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.RETENCION (RetId,RetHab,RetUltNro,RetImpMin,RetIva,RetRen,Ret2051,RetImp,RetIvaCta,RetRenCta,RetLeyCta,RetUsr,RetNroFac,RetNroTim,RetIva05,RetIvaCta05)\n" +
                            "select RetId,RetHab,RetUltNro,RetImpMin,RetIva,RetRen,Ret2051,RetImp,RetIvaCta,RetRenCta,RetLeyCta,RetUsr,RetNroFac,RetNroTim,RetIva05,RetIvaCta05 from "+Conexion.conexionorivar+".dbo.RETENCION");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en RETENCION "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                        
                    break;
                    case"SOLPAG":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.SOLPAG\n" +
                            "SET IDENTITY_INSERT SOLPAG ON\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.SOLPAG (SolPagId,SolPagSuc,SolPagFec,SolPagBen,SolPagImp,SolPagCon,SolPagEmp,SolPagUsr,SolPagNroAst)\n" +
                            "select SolPagId,SolPagSuc,SolPagFec,SolPagBen,SolPagImp,SolPagCon,SolPagEmp,SolPagUsr,SolPagNroAst FROM "+Conexion.conexionorivar+".dbo.SOLPAG\n" +
                            "SET IDENTITY_INSERT SOLPAG OFF");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en SOLPAG "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                        
                    break;
                    case"SUCURSAL":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.SUCURSAL\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.SUCURSAL (SucId,SucEmp,SucUsr,SucNom,SucNomRes,SucTel,SucConsol)\n" +
                            "select SucId,SucEmp,SucUsr,SucNom,SucNomRes,SucTel,SucConsol from "+Conexion.conexionorivar+".dbo.SUCURSAL");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en SUCURSAL "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                        
                    break;
                    case"TRNFCTA":
                        try {
                            Connection con = ConexionDes.GetConnection();
                            PreparedStatement psql=con.prepareStatement("DELETE FROM "+Conexion.conexiondesvar+".dbo.TRNFCTA\n" +
                            "SET IDENTITY_INSERT TRNFCTA ON\n" +
                            "Insert Into "+Conexion.conexiondesvar+".dbo.TRNFCTA (TrnfId,TrnfUsr,TrnfEmp,TrnfSuc,TrnfFec,TrnfdeBco,TrnfaBco,TrnfdeOp,TrnfaOp,TrnfImp,TrnfImpMe,TrnfMon,TrnfVal,TrnfCnc,TrnfMonEx,TrnfOri,TrnfEstDepImp,TrnfEstExtImp,TrnfNroAst,TrnfGen,TRnfBene,TrnDepoID)\n" +
                            "select TrnfId,TrnfUsr,TrnfEmp,TrnfSuc,TrnfFec,TrnfdeBco,TrnfaBco,TrnfdeOp,TrnfaOp,TrnfImp,TrnfImpMe,TrnfMon,TrnfVal,TrnfCnc,TrnfMonEx,TrnfOri,TrnfEstDepImp,TrnfEstExtImp,TrnfNroAst,TrnfGen,TRnfBene,TrnDepoID FROM "+Conexion.conexionorivar+".dbo.TRNFCTA\n" +
                            "SET IDENTITY_INSERT TRNFCTA OFF");                              
                            psql.execute();
                            psql.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error en TRNFCTA "+ex.getMessage(), JOptionPane.ERROR_MESSAGE);                
                        }                        
                    break;
                }
            }
        cargagriddes();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
